      SUBROUTINE GROUPS( GVALUE, LGVALU, FVALUE, GPVALU, NCALCG, 
     *                   ITYPEG, ISTGPA, ICALCG, DERIVS )
      INTEGER LGVALU, NCALCG
      LOGICAL DERIVS
      INTEGER ITYPEG(*), ISTGPA(*), ICALCG(*)
      DOUBLE PRECISION GVALUE(LGVALU,3), FVALUE(*), GPVALU(*)
C
C  PROBLEM NAME : HS9     
C
      RETURN
      END
