      SUBROUTINE GROUPS( GVALUE, LGVALU, FVALUE, GPVALU, NCALCG, 
     *                   ITYPEG, ISTGPA, ICALCG, DERIVS )
      INTEGER LGVALU, NCALCG
      LOGICAL DERIVS
      INTEGER ITYPEG(*), ISTGPA(*), ICALCG(*)
      DOUBLE PRECISION GVALUE(LGVALU,3), FVALUE(*), GPVALU(*)
C
C  PROBLEM NAME : AUG2D   
C
      INTEGER IGRTYP, IGROUP, IPSTRT, JCALCG
      DOUBLE PRECISION ALPHA 
      DO     2 JCALCG = 1, NCALCG
       IGROUP = ICALCG(JCALCG)
       IGRTYP = ITYPEG(IGROUP)
       IF ( IGRTYP .EQ. 0 ) GO TO     2
       IPSTRT = ISTGPA(IGROUP) - 1
C
C  GROUP TYPE : SQUARE  
C
       ALPHA = FVALUE(IGROUP)
       IF ( .NOT. DERIVS ) THEN
        GVALUE(IGROUP,1)= 5.0D-1 * ALPHA * ALPHA                   
       ELSE
        GVALUE(IGROUP,2)= ALPHA                                    
        GVALUE(IGROUP,3)= 1.0D+0                                   
       END IF
    2 CONTINUE
      RETURN
      END
